load(file = "../../data/ideb_repasse/fundeb/todos_anos.RData")

write.csv(ideb_repasse %>% dplyr::filter(UF == "AC"), "../../data/ideb_repasse/fundeb/estado/AC.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "AP"), "../../data/ideb_repasse/fundeb/estado/AP.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "AM"), "../../data/ideb_repasse/fundeb/estado/AM.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "RO"), "../../data/ideb_repasse/fundeb/estado/RO.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "RR"), "../../data/ideb_repasse/fundeb/estado/RR.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "TO"), "../../data/ideb_repasse/fundeb/estado/TO.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "AL"), "../../data/ideb_repasse/fundeb/estado/AL.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "BA"), "../../data/ideb_repasse/fundeb/estado/BA.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "CE"), "../../data/ideb_repasse/fundeb/estado/CE.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "MA"), "../../data/ideb_repasse/fundeb/estado/MA.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "PB"), "../../data/ideb_repasse/fundeb/estado/PB.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "PI"), "../../data/ideb_repasse/fundeb/estado/PI.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "PE"), "../../data/ideb_repasse/fundeb/estado/PE.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "RN"), "../../data/ideb_repasse/fundeb/estado/RN.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "SE"), "../../data/ideb_repasse/fundeb/estado/SE.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "DF"), "../../data/ideb_repasse/fundeb/estado/DF.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "GO"), "../../data/ideb_repasse/fundeb/estado/GO.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "MT"), "../../data/ideb_repasse/fundeb/estado/MT.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "MS"), "../../data/ideb_repasse/fundeb/estado/MS.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "ES"), "../../data/ideb_repasse/fundeb/estado/ES.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "SP"), "../../data/ideb_repasse/fundeb/estado/SP.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "MG"), "../../data/ideb_repasse/fundeb/estado/MG.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "RJ"), "../../data/ideb_repasse/fundeb/estado/RJ.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "PR"), "../../data/ideb_repasse/fundeb/estado/PR.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "RS"), "../../data/ideb_repasse/fundeb/estado/RS.csv")
write.csv(ideb_repasse %>% dplyr::filter(UF == "SC"), "../../data/ideb_repasse/fundeb/estado/SC.csv")
